##### deployement on cpanel
---
deployment:
  tasks:
    - /opt/alt/alt-node/js20/root/usr/bin/npm run generate
    - export DEPLOYPATH=/home/eheq1939/nocolowcobill.lc-consult.fr/
    - /bin/cp -R dist $DEPLOYPATH